version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/tcc
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: ubuntu
