<div id="credits-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <section class="modal-content">
            <header class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h1 class="modal-title">Créditos</h1>
            </header>
            <div class="modal-body">
                <p>
                    Feito por: <b>Victor Nagase</b> e <b>William Carril</b>
                </p>
                <section data-role="credits">
                    <h2>Referências</h2>
                    Font generated by <a href="http://www.flaticon.com">flaticon.com</a>. <p>Under <a href="http://creativecommons.org/licenses/by/3.0/">CC</a>: <a data-file="gps" href="http://www.flaticon.com/authors/daniel-bruce">Daniel Bruce</a>, <a data-file="smile" href="http://www.flaticon.com/authors/google">Google</a>, <a data-file="key" href="http://www.flaticon.com/authors/freepik">Freepik</a>, <a data-file="user" href="http://www.flaticon.com/authors/freepik">Freepik</a>, <a data-file="walker" href="http://www.freepik.com">Freepik</a></p>  
                    FlatIcon <a href="{{asset("etc/flaticon_license.pdf")}}">licence</a>.
                </section>
            </div>
            <footer class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </footer>
        </section>
    </div>
</div>